server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      dead-letter:
        producer: dl.producer.aula-spring
      exchange:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
